---
- name: Install Longhorn
  hosts: k3s_servers[0]
  become: true
  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    longhorn_version: 1.6.2
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  tasks:
    - shell: kubectl get nodes
      retries: 20
      delay: 10
      register: r
      until: r.rc == 0

    - shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - shell: |
        helm repo add longhorn https://charts.longhorn.io
        helm repo update

    - shell: |
        kubectl create ns longhorn-system || true
        helm upgrade --install longhorn longhorn/longhorn \
          --namespace longhorn-system \
          --version {{ longhorn_version }}